have_fun: false
code_review:
  disable: false
  comment_severity_threshold: 'HIGH'
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: true
    code_review: true
ignore_patterns: []
tools:
  run_shell_command:
    allowed_commands:
      - poetry
      - mkdir
      - rm
      - cp
      - rmdir
      - ls
      - find
      - grep
      - rg
      